---
DEFAULT_BRANCH: main
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: ".release-please-manifest.json"
MARKDOWN_FILTER_REGEX_EXCLUDE: "CHANGELOG.md"
VALIDATE_ALL_CODEBASE: false
DISABLE:
  - COPYPASTE
  - SPELL
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true
APPLY_FIXES: all
