name: MC-Runtime-Test
description: Runs the MC client inside your CI
author: HeadlessHQ
branding:
  icon: play
  color: green

inputs:
  mc:
    description: Minecraft version to run
    required: true
  modloader:
    description: Modloader to install (forge, neoforge, fabric)
    required: true
  regex:
    description: Regex to match the modloader jar (i.e. .*fabric.*)
    required: true
  java:
    description: Java version to use (8, 16, 17, 21)
    required: true
  dummy-assets:
    description: Use dummy assets during testing
    default: "true"
  mc-runtime-test:
    description: MC-Runtime-Test jar to download (none, lexforge, neoforge, fabric)
    required: true
  xvfb:
    description: Runs the game with Xvfb (if false, add the -lwjgl argument)
    default: "true"
  headlessmc-command:
    description: Command-line arguments for HeadlessMC
    default: '--jvm "-Djava.awt.headless=true"'
  fabric-api:
    description: Fabric API version to download (e.g. 0.97.0) or none
    default: "none"
  fabric-gametest-api:
    description: Fabric GameTest API version (e.g. 1.3.5+85d85a934f) or none
    default: "none"
  download-hmc:
    description: Download HeadlessMC
    default: "true"
  hmc-version:
    description: HeadlessMC version
    default: "2.4.1"
  cache-mc:
    description: Cache .minecraft
    default: "true"

runs:
  using: composite
  steps:
    - name: Bootstrap HeadlessMC
      run: |
        mkdir -p HeadlessMC run/mods
        cat <<EOF >> HeadlessMC/config.properties
        hmc.java.versions=$JAVA_HOME/bin/java
        hmc.gamedir=$PWD/run
        hmc.offline=true
        hmc.rethrow.launch.exceptions=true
        hmc.exit.on.failed.command=true
        EOF
      shell: bash

    - if: inputs.dummy-assets == 'true'
      name: Configure Dummy Assets
      run: echo hmc.assets.dummy=true >> HeadlessMC/config.properties
      shell: bash

    - if: inputs.download-hmc == 'true'
      name: Get HeadlessMC
      uses: robinraju/release-downloader@v1.11
      with:
        repository: 3arthqu4ke/headlessmc
        tag: ${{ inputs.hmc-version }}
        fileName: headlessmc-launcher-${{ inputs.hmc-version }}.jar

    - if: inputs.cache-mc == 'true'
      name: Cache Minecraft
      uses: actions/cache@v4
      with:
        path: /home/runner/.minecraft
        key: hmc-${{ inputs.modloader }}-${{ inputs.mc }}

    - name: Download ${{ inputs.modloader }}-${{ inputs.mc }}
      run: |
        if [ ! -f "$HOME/.minecraft/versions/${{ inputs.mc }}/${{ inputs.mc }}.json" ]; then
          java -jar headlessmc-launcher-${{ inputs.hmc-version }}.jar --command download ${{ inputs.mc }}
          java -jar headlessmc-launcher-${{ inputs.hmc-version }}.jar --command ${{ inputs.modloader }} ${{ inputs.mc }} --java ${{ inputs.java }}
        fi
      shell: bash

    - id: get-mcrt
      if: inputs.mc-runtime-test != 'none'
      name: Get mc-runtime-test
      uses: robinraju/release-downloader@v1.11
      with:
        repository: headlesshq/mc-runtime-test
        tag: "3.0.0" # x-release-please-version
        fileName: 'mc-runtime-test-${{ inputs.mc }}-*-${{ inputs.mc-runtime-test }}-release.jar'
        out-file-path: run/mods

    - if: inputs.fabric-api != 'none'
      name: Download fabric-api v${{ inputs.fabric-api }}
      run: >
        wget -O run/mods/fabric-api-${{ inputs.fabric-api }}+${{ inputs.mc }}.jar
        https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/${{ inputs.fabric-api }}+${{ inputs.mc }}/fabric-api-${{ inputs.fabric-api }}+${{ inputs.mc }}.jar
      shell: bash

    - if: inputs.fabric-gametest-api != 'none'
      name: Download fabric-gametest-api v${{ inputs.fabric-gametest-api }}
      run: >
        wget -O run/mods/fabric-gametest-api-v1-${{ inputs.fabric-gametest-api }}.jar
        https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-gametest-api-v1/${{ inputs.fabric-gametest-api }}/fabric-gametest-api-v1-${{ inputs.fabric-gametest-api }}.jar
      shell: bash

    - name: Configure game
      run: |
        cat <<EOF >> run/options.txt
        onboardAccessibility:false
        pauseOnLostFocus:false
        EOF
      shell: bash

    - if: inputs.xvfb == 'true'
      name: Run game with xvfb
      run: | # TODO: install xrandr conditionally per #22
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y x11-xserver-utils
        xvfb-run java -Dhmc.check.xvfb=true -jar headlessmc-launcher-${{ inputs.hmc-version }}.jar --command launch ${{ inputs.regex }} -regex ${{ inputs.headlessmc-command }}
      shell: bash

    - if: inputs.xvfb != 'true'
      name: Run game
      run: java -jar headlessmc-launcher-${{ inputs.hmc-version }}.jar --command launch ${{ inputs.regex }} -regex ${{ inputs.headlessmc-command }}
      shell: bash
