name: 'Local Run Action'
description: 'Runs the Minecraft client'
inputs:
    mc:
      description: 'The Minecraft version to run'
      required: true
      default: '1.20.4'
    modloader:
      description: 'The modloader to install with HeadlessMc (forge, neoforge or fabric)'
      required: true
      default: 'fabric'
    regex:
      description: 'Regex to match the Minecraft version to launch (forge is like 1.20.4-forge and fabric starts with fabric-1.20)'
      required: true
      default: '.*fabric.*'
    java:
      description: 'The Java version to use'
      required: true
      default: '17'
    dummy_assets:
      description: 'Whether to use Dummy Assets or not'
      required: true
      default: 'true'
    mc_runtime_test:
      description: 'The mc_runtime_test jar to download (none, lexforge, fabric or neoforge)'
      required: true
      default: 'fabric'

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java }}
        distribution: adopt
    - name: Setup HeadlessMC directory
      run: mkdir HeadlessMC
      shell: bash
    - name: Configure HeadlessMC java versions
      run: echo hmc.java.versions=$JAVA_HOME/bin/java > HeadlessMC/config.properties
      shell: bash
    - name: Configure HeadlessMC game directory
      run: echo hmc.gamedir=$PWD/run >> HeadlessMC/config.properties
      shell: bash
    - name: Configure offline mode
      run: echo hmc.offline=true >> HeadlessMC/config.properties
      shell: bash
    - name: Configure Exceptions
      run: echo hmc.rethrow.launch.exceptions=true >> HeadlessMC/config.properties
      shell: bash
    - name: Configure Failing on wrong command
      run: echo hmc.exit.on.failed.command=true >> HeadlessMC/config.properties
      shell: bash
    - name: Configure Dummy Assets
      if: ${{ inputs.dummy_assets == 'true' }}
      run: echo hmc.assets.dummy=true >> HeadlessMC/config.properties
      shell: bash
    - name: Get HeadlessMC
      run: wget -O headlessmc-launcher-1.9.5.jar https://github.com/3arthqu4ke/headlessmc/releases/download/1.9.5/headlessmc-launcher-1.9.5.jar
      shell: bash
    - name: Download ${{ inputs.mc }}
      run: java -jar headlessmc-launcher-1.9.5.jar --command download ${{ inputs.mc }}
      shell: bash
    - name: Download Fabric ${{ inputs.mc }}
      run: java -jar headlessmc-launcher-1.9.5.jar --command ${{ inputs.modloader }} ${{ inputs.mc }} --java ${{ inputs.java }}
      shell: bash
    - name: List versions
      run: java -jar headlessmc-launcher-1.9.5.jar --command versions
      shell: bash
    - name: Make mods dir
      run: mkdir -p run/mods
      shell: bash
    - name: Download mc-runtime-test jar ${{ inputs.mc_runtime_test }}
      if: ${{ inputs.mc_runtime_test != 'none' }}
      run: wget -O run/mods/mc-runtime-test-${{ inputs.mc }}-0.2.0-${{ inputs.mc_runtime_test }}-release.jar https://github.com/3arthqu4ke/mc-runtime-test/releases/download/0.2.0/mc-runtime-test-${{ inputs.mc }}-0.2.0-${{ inputs.mc_runtime_test }}-release.jar
      shell: bash
    - name: Configure Accessibility
      run: echo onboardAccessibility:false >> run/options.txt
      shell: bash
    - name: LS mods dir
      run: ls run/mods
      shell: bash
    - name: Run game
      run: java -jar headlessmc-launcher-1.9.5.jar --command launch ${{ inputs.regex }} -regex -lwjgl --jvm -Djava.awt.headless=true
      shell: bash
