modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/headlesshq/mc-runtime-test"
license = "MIT"

[[mods]]
modId = "clientgametest"
version = "${version}"
displayName = "GameTest"
authors = "3arthqu4ke"
description = '''
    Mod to test the Minecraft clientgametest framework
'''

[[dependencies.clientgametest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.6]"
ordering = "NONE"
side = "BOTH"
