name: Build Matrix 1.18+
on: 
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [ {mc: 1.18.2, lex: 40.2.18}, {mc: 1.18.1, lex: 39.1.2}, {mc: 1.18, lex: 38.0.17} ]
      steps:
        -   uses: actions/checkout@v2
        -   uses: actions/setup-java@v2
            with:
                java-version: 17
                distribution: adopt
        -   name: Grant execute permission for gradlew
            working-directory: ./1_19
            run: chmod +x gradlew
        -   name: Build
            working-directory: ./1_19
            run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }}
