name: Build All With Artifacts
on:
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        strategy:
            matrix:
                version:
                    - { dir: api, mc: api, lex: api, neo: api, java: 8 }
                    - { dir: 1_21, mc: 1.21.3, lex: 53.0.7, neo: 11-beta, java: 21 }
                    - { dir: 1_21, mc: 1.21.1, lex: 52.0.2, neo: 4, java: 21 }
                    - { dir: 1_21, mc: 1.21, lex: 51.0.24, neo: 96-beta, java: 21 }
                    - { dir: 1_20/1_20_6, mc: 1.20.6, lex: 50.1.10, neo: 119, java: 21 }
                    - { dir: 1_20, mc: 1.20.4, lex: 49.0.38, neo: 219, java: 17 }
                    - { dir: 1_20, mc: 1.20.3, lex: 49.0.2, neo: 8-beta, java: 17 }
                    - { dir: 1_20, mc: 1.20.2, lex: 48.1.0, neo: 88, java: 17 }
                    - { dir: 1_20/1_20_1, mc: 1.20.1, lex: 47.2.23, neo: 0, java: 17 }
                    - { dir: 1_19, mc: 1.19.4, lex: 45.2.9, neo: 0, java: 17 }
                    - { dir: 1_19, mc: 1.19.3, lex: 44.1.23, neo: 0, java: 17 }
                    - { dir: 1_19, mc: 1.19.2, lex: 43.3.9, neo: 0, java: 17 }
                    - { dir: 1_19, mc: 1.19.1, lex: 42.0.9, neo: 0, java: 17 }
                    - { dir: 1_19, mc: 1.19, lex: 41.1.0, neo: 0, java: 17 }
                    - { dir: 1_18, mc: 1.18.2, lex: 40.2.18, neo: 0, java: 17 }
                    - { dir: 1_17, mc: 1.17.1, lex: 37.1.1, neo: 0, java: 16 }
                    - { dir: 1_16, mc: 1.16.5, lex: 36.2.42, neo: 0, java: 8 }
                    - { dir: 1_12, mc: 1.12.2, lex: 14.23.5.2860, neo: 0, java: 8 }
                    - { dir: 1_8_9, mc: 1.8.9, lex: 11.15.1.2318-1.8.9, neo: 0, java: 8 }
                    - { dir: 1_7_10, mc: 1.7.10, lex: 10.13.4.1614-1.7.10, neo: 0, java: 8 }
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: ${{ matrix.version.java }}
                  distribution: adopt
            - name: Grant execute permission for gradlew
              working-directory: ./${{ matrix.version.dir }}
              run: chmod +x gradlew
            - name: Build
              working-directory: ./${{ matrix.version.dir }}
              run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }} -Pneoforge_version=${{ matrix.version.neo }} --stacktrace
            - name: Upload ${{ matrix.version.mc }} Jars
              uses: actions/upload-artifact@v4
              with:
                  name: jars-${{ matrix.version.mc }}
                  path: ./${{ matrix.version.dir }}/build/libs/*.jar

    merge:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Merge Artifacts
              uses: actions/upload-artifact/merge@v4
              with:
                delete-merged: true
                