name: Build Matrix 1.7+
on: 
    workflow_dispatch:
    workflow_call:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [ {mc: 1.7.10, lex: 10.13.4.1614-1.7.10} ]
      steps:
        -   uses: actions/checkout@v2
        -   uses: actions/setup-java@v2
            with:
                java-version: 8
                distribution: adopt
        -   name: Grant execute permission for gradlew
            working-directory: ./1_7_10
            run: chmod +x gradlew
        -   name: Build
            working-directory: ./1_7_10
            run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }}
