name: Build Matrix 1.16+
on: 
    workflow_dispatch:
    workflow_call:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [ {mc: 1.16.5, lex: 36.2.42} ]
          #version: [ {mc: 1.16.5, lex: 36.2.42}, {mc: 1.16.4, lex: 35.1.37}, {mc: 1.16.3, lex: 34.1.42}, {mc: 1.16.2, lex: 33.0.61}, {mc: 1.16.1, lex: 32.0.108} ]
      steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-java@v4
            with:
                java-version: 8
                distribution: adopt
        -   name: Grant execute permission for gradlew
            working-directory: ./1_16
            run: chmod +x gradlew
        -   name: Build
            working-directory: ./1_16
            run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }} --stacktrace
