name: Build specific version
on: 
    workflow_dispatch:
      inputs:
        mc:
          description: 'The Minecraft version to build'
          required: true
          default: '1.20.4'
        lex:
          description: 'The LexForge version to use'
          required: true
          default: '49.0.38'
        neo:
          description: 'The NeoForge version to use'
          required: true
          default: '219'
          
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        -   uses: actions/checkout@v2
        -   uses: actions/setup-java@v2
            with:
                java-version: 17
                distribution: adopt
        -   name: Grant execute permission for gradlew
            run: chmod +x gradlew
        -   name: Build
            run: ./gradlew build -Pminecraft_version=${{ github.event.inputs.mc }} -Plexforge_version=${{ github.event.inputs.lex }} -Pneoforge_version=${{ github.event.inputs.neo }}
