name: Build Matrix 1.20+
on: 
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [ {mc: 1.20.4, lex: 49.0.38, neo: 219}, {mc: 1.20.3, lex: 49.0.2, neo: 8-beta}, {mc: 1.20.2, lex: 48.1.0, neo: 88} ]
      steps:
        -   uses: actions/checkout@v2
        -   uses: actions/setup-java@v2
            with:
                java-version: 17
                distribution: adopt
        -   name: Grant execute permission for gradlew
            run: chmod +x gradlew
        -   name: Build
            run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }} -Pneoforge_version=${{ matrix.version.neo }}
