name: Build Matrix 1.8+
on: 
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [ {mc: 1.8.9, lex: 11.15.1.2318-1.8.9} ]
      steps:
        -   uses: actions/checkout@v2
        -   uses: actions/setup-java@v2
            with:
                java-version: 8
                distribution: adopt
        -   name: Grant execute permission for gradlew
            working-directory: ./1_8_9
            run: chmod +x gradlew
        -   name: Build
            working-directory: ./1_8_9
            run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }}
