name: Build specific version
on:
    workflow_dispatch:
      inputs:
        dir:
          description: 'The directory to build in'
          required: true
          default: '1_20'
        mc:
          description: 'The Minecraft version to build'
          required: true
          default: '1.20.4'
        lex:
          description: 'The LexForge version to use'
          required: true
          default: '49.0.38'
        neo:
          description: 'The NeoForge version to use'
          required: true
          default: '219'
        java:
          description: 'The Java version to use'
          required: true
          default: '17'
          
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-java@v4
            with:
                java-version: ${{ github.event.inputs.java }}
                distribution: adopt
        -   name: Grant execute permission for gradlew
            working-directory: ./${{ github.event.inputs.dir }}
            run: chmod +x gradlew
        -   name: Build
            working-directory: ./${{ github.event.inputs.dir }}
            run: ./gradlew build -Pminecraft_version=${{ github.event.inputs.mc }} -Plexforge_version=${{ github.event.inputs.lex }} -Pneoforge_version=${{ github.event.inputs.neo }}
        -   name: Upload Jars
            uses: actions/upload-artifact@v4
            with:
              name: Artifacts
              path: ./${{ inputs.dir }}/build/libs/*.jar
            