name: Build Matrix 1.21+
on: 
    workflow_dispatch:
    workflow_call:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [ {mc: 1.21, lex: 51.0.24, neo: 96-beta} ]
      steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-java@v4
            with:
                java-version: 21
                distribution: adopt
        -   name: Grant execute permission for gradlew
            working-directory: ./1_21
            run: chmod +x gradlew
        -   name: Build
            working-directory: ./1_21
            run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }} -Pneoforge_version=${{ matrix.version.neo }}
