name: Build Matrix 1.20+
on: 
    workflow_dispatch:
    workflow_call:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [ {mc: 1.20.6, lex: 50.1.10, neo: 119} ]
      steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-java@v4
            with:
                java-version: 17
                distribution: adopt
        -   name: Grant execute permission for gradlew
            working-directory: ./1_20/1_20_6
            run: chmod +x gradlew
        -   name: Build
            working-directory: ./1_20/1_20_6
            run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }} -Pneoforge_version=${{ matrix.version.neo }} --stacktrace
