name: Build specific version reusable
on:
  workflow_call:
    inputs:
      dir:
        description: 'The directory to build in'
        required: true
        default: '1_20'
        type: string
      mc:
        description: 'The MC version to build'
        required: true
        default: '1.20.4'
        type: string
      lex:
        description: 'The LexForge version to use'
        required: true
        default: '49.0.38'
        type: string
      neo:
        description: 'The NeoForge version to use'
        required: true
        default: '219'
        type: string
      java:
        description: 'The Java version to use'
        required: true
        default: '17'
        type: string
      java-distribution:
        description: 'The Java distribution to use'
        required: false
        default: 'adopt'
        type: string
      upload:
        description: 'Uploads the artifacts from the build'
        required: false
        default: 'true'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java }}
          distribution: ${{ inputs.java-distribution }}
      - name: Grant execute permission for gradlew
        working-directory: ./${{ inputs.dir }}
        run: chmod +x gradlew
      - name: Build
        working-directory: ./${{ inputs.dir }}
        run: ./gradlew build -Pminecraft_version=${{ inputs.mc }} -Plexforge_version=${{ inputs.lex }} -Pneoforge_version=${{ inputs.neo }} --stacktrace
      - name: Upload ${{ matrix.version.mc }} Jars
        if: ${{ inputs.upload == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ inputs.mc }}
          path: ./${{ inputs.dir }}/build/libs/*.jar
