name: Build Matrix 1.17+
on: 
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [ {mc: 1.17.1, lex: 37.1.1} ]
      steps:
        -   uses: actions/checkout@v2
        -   uses: actions/setup-java@v2
            with:
                java-version: 16
                distribution: adopt
        -   name: Grant execute permission for gradlew
            working-directory: ./1_17
            run: chmod +x gradlew
        -   name: Build
            working-directory: ./1_17
            run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }}
