name: Run Fabric Client
on: 
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v4
                id: setup-java-17
                with:
                    java-version: 17
                    distribution: adopt
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Echo jdk
                run: echo "${{ steps.setup-java-17.outputs.jdk-path }}"
            -   name: Ls jdk
                run: ls "${{ steps.setup-java-17.outputs.jdk-path }}"
