name: Run Fabric Client
on: 
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v4
                id: setup-java-17
                with:
                    java-version: 17
                    distribution: adopt
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Setup HeadlessMC directory
                run: mkdir HeadlessMC
            -   name: Configure HeadlessMC java versions
                run: echo hmc.java.versions=$JAVA_HOME/bin/java > HeadlessMC/config.properties
            -   name: Configure HeadlessMC game directory
                run: echo hmc.gamedir=$PWD/run >> HeadlessMC/config.properties
            -   name: Configure offline mode
                run: echo hmc.offline=true >> HeadlessMC/config.properties
            -   name: Setup game args
                run: echo hmc.gameargs=--quickPlaySingleplayer Test >> HeadlessMC/config.properties
            -   name: Get HeadlessMC
                run: wget headlessmc-launcher-1.9.1.jar https://github.com/3arthqu4ke/headlessmc/releases/download/1.9.1/headlessmc-launcher-1.9.1.jar
            -   name: Download 1.20.4
                run: java -jar headlessmc-launcher-1.9.1.jar --command download 1.20.4
            -   name: Download Fabric 1.20.4
                run: java -jar headlessmc-launcher-1.9.1.jar --command fabric 1.20.4
            -   name: List versions
                run: java -jar headlessmc-launcher-1.9.1.jar --command versions
            -   name: Make mods dir
                run: mkdir /run/mods
            -   name: Build
                run: ./gradlew build
            -   name: Copy mod
                run: cp build/libs/mc-runtime-test-0.1.0-fabric-release.jar run/mods
            -   name: Run game
                run: java -jar headlessmc-launcher-1.9.1.jar --command launch fabric-loader-0.15.9-1.20.4 -lwjgl
