name: Run Fabric 1.20.4
on: 
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                id: setup-java-17
                with:
                    java-version: 17
                    distribution: adopt
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Setup HeadlessMC directory
                run: mkdir HeadlessMC
            -   name: Configure HeadlessMC java versions
                run: echo hmc.java.versions=$JAVA_HOME/bin/java > HeadlessMC/config.properties
            -   name: Configure HeadlessMC game directory
                run: echo hmc.gamedir=$PWD/run >> HeadlessMC/config.properties
            -   name: Configure offline mode
                run: echo hmc.offline=true >> HeadlessMC/config.properties
            -   name: Configure Exceptions
                run: echo hmc.rethrow.launch.exceptions=true >> HeadlessMC/config.properties
            -   name: Configure Failing on wrong command
                run: echo hmc.exit.on.failed.command=true >> HeadlessMC/config.properties
            -   name: Configure Dummy Assets
                run: echo hmc.assets.dummy=true >> HeadlessMC/config.properties
            -   name: Get HeadlessMC
                run: wget -O headlessmc-launcher-1.10.0.jar https://github.com/3arthqu4ke/headlessmc/releases/download/1.10.0/headlessmc-launcher-1.10.0.jar
            -   name: Download 1.20.4
                run: java -jar headlessmc-launcher-1.10.0.jar --command download 1.20.4
            -   name: Download Fabric 1.20.4
                run: java -jar headlessmc-launcher-1.10.0.jar --command fabric 1.20.4
            -   name: List versions
                run: java -jar headlessmc-launcher-1.10.0.jar --command versions
            -   name: Make mods dir
                run: mkdir -p run/mods
            -   name: Configure Accessibility
                run: echo onboardAccessibility:false >> run/options.txt
            -   name: Build
                run: ./gradlew build
            -   name: Copy mod
                run: cp build/libs/mc-runtime-test-*-fabric-release.jar run/mods
            -   name: LS mods dir
                run: ls run/mods
            -   name: Run game
                run: java -jar headlessmc-launcher-1.10.0.jar --command launch fabric.*1.20.4 -regex -lwjgl --jvm -Djava.awt.headless=true
