---
name: Flex Build

"on":
  workflow_call:
    inputs:
      dir:
        description: Directory to build
        required: true
        type: string
      mc:
        description: Minecraft version
        type: string
      lex:
        description: LexForge version
        type: string
      neo:
        description: NeoForge version
        type: string
      java:
        description: Java version
        required: true
        type: string
      upload:
        description: Upload the build artifacts
        default: true
        type: boolean
      publish:
        description: Run Gradle publish
        default: false
        type: boolean

jobs:
  build: # TODO: add build attestation and generate then combine gradle dependency graphs for SBOM
    name: Build ${{ inputs.dir }}/${{ inputs.mc }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            api
            ${{ inputs.dir }}

      - name: Cache build
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dir }}/build
          key: build-${{ hashFiles(format('{0}/[a-z]**', inputs.dir), 'api/**') }}

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java }}

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          workflow-job-context: '{}' # FIXME: avoid this cache duplication workaround

      - if: |
          steps.cache.outputs.cache-hit != 'true'
          && !inputs.release
        name: Gradle build
        run: >
          ./gradlew build --stacktrace
          -Pminecraft_version=${{ inputs.mc }}
          -Plexforge_version=${{ inputs.lex }}
          -Pneoforge_version=${{ inputs.neo }}
        working-directory: ${{ inputs.dir }}

      - if: inputs.release
        name: Gradle publish
        env:
          IS_MAVEN_PUB: true
          DEPLOY_TO_GITHUB_PACKAGES_URL: https://maven.pkg.github.com/${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish
        working-directory: ${{ inputs.dir }}

      - if: inputs.upload
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ inputs.mc || inputs.dir }}${{ inputs.dir == 'gametest' && '-gametest' || '' }}
          path: ${{ inputs.dir }}/build/libs/*.jar
