name: Publish API to github packages

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
      - name: Grant execute permission for gradlew
        working-directory: ./api
        run: chmod +x gradlew
      - name: Publish with gradle
        working-directory: ./api
        env:
          IS_MAVEN_PUB: true
          DEPLOY_TO_GITHUB_PACKAGES_URL: https://maven.pkg.github.com/3arthqu4ke/mc-runtime-test
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew publish
