---
name: Publish API

"on":
  release:
    types: [created]

jobs:
  publish-api:
    name: Publish API
    uses: ./.github/workflows/flex-build.yml
    with:
      dir: api
      java: 8
      publish: true
      upload: false
