name: Run all versions
on:
  workflow_dispatch:
  workflow_call:

jobs:
  RunMinecraft:
    strategy:
      matrix:
        version: [ { dir: 1_20, mc: 1.20.4, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 } ]
    uses: 3arthqu4ke/mc-runtime-test/.github/workflows/run-specific-reusable.yml@main
    with:
      dir: ${{ matrix.version.dir }}
      mc: ${{ matrix.version.mc }}
      type: ${{ matrix.version.type }}
      modloader: ${{ matrix.version.modloader }}
      regex: ${{ matrix.version.regex }}
      java: ${{ matrix.version.java }}
