name: Run all versions
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - { dir: api, mc: api, lex: api, neo: api, java: 8 }
          - { dir: 1_21, mc: 1.21.3, lex: 53.0.7, neo: 11-beta, java: 21 }
          - { dir: 1_21, mc: 1.21.1, lex: 52.0.2, neo: 4, java: 21 }
          - { dir: 1_21, mc: 1.21, lex: 51.0.24, neo: 96-beta, java: 21 }
          - { dir: 1_20/1_20_6, mc: 1.20.6, lex: 50.1.10, neo: 119, java: 21 }
          - { dir: 1_20, mc: 1.20.4, lex: 49.0.38, neo: 219, java: 17 }
          - { dir: 1_20, mc: 1.20.3, lex: 49.0.2, neo: 8-beta, java: 17 }
          - { dir: 1_20, mc: 1.20.2, lex: 48.1.0, neo: 88, java: 17 }
          - { dir: 1_20/1_20_1, mc: 1.20.1, lex: 47.2.23, neo: 0, java: 17 }
          - { dir: 1_19, mc: 1.19.4, lex: 45.2.9, neo: 0, java: 17 }
          - { dir: 1_19, mc: 1.19.3, lex: 44.1.23, neo: 0, java: 17 }
          - { dir: 1_19, mc: 1.19.2, lex: 43.3.9, neo: 0, java: 17 }
          - { dir: 1_19, mc: 1.19.1, lex: 42.0.9, neo: 0, java: 17 }
          - { dir: 1_19, mc: 1.19, lex: 41.1.0, neo: 0, java: 17 }
          - { dir: 1_18, mc: 1.18.2, lex: 40.2.18, neo: 0, java: 17 }
          - { dir: 1_17, mc: 1.17.1, lex: 37.1.1, neo: 0, java: 16 }
          - { dir: 1_16, mc: 1.16.5, lex: 36.2.42, neo: 0, java: 8 }
          - { dir: 1_12, mc: 1.12.2, lex: 14.23.5.2860, neo: 0, java: 8 }
          - { dir: 1_8_9, mc: 1.8.9, lex: 11.15.1.2318-1.8.9, neo: 0, java: 8 }
          - { dir: 1_7_10, mc: 1.7.10, lex: 10.13.4.1614-1.7.10, neo: 0, java: 8 }
      fail-fast: false
    uses: 3arthqu4ke/mc-runtime-test/.github/workflows/build-specific-reusable.yml@main
    with:
      dir: ${{ matrix.version.dir }}
      mc: ${{ matrix.version.mc }}
      lex: ${{ matrix.version.lex }}
      neo: ${{ matrix.version.neo }}
      java: ${{ matrix.version.java }}

  run:
    needs: build
    strategy:
      matrix:
        version:
          - { dir: 1_21, mc: 1.21.3, type: lexforge, modloader: forge, regex: .*forge.*, java: 21 }
          - { dir: 1_21, mc: 1.21.3, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 21 }
          - { dir: 1_21, mc: 1.21.3, type: fabric, modloader: fabric, regex: .*fabric.*, java: 21 }
          - { dir: 1_21, mc: 1.21.1, type: lexforge, modloader: forge, regex: .*forge.*, java: 21 }
          - { dir: 1_21, mc: 1.21.1, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 21 }
          - { dir: 1_21, mc: 1.21.1, type: fabric, modloader: fabric, regex: .*fabric.*, java: 21 }
          - { dir: 1_21, mc: 1.21, type: lexforge, modloader: forge, regex: .*forge.*, java: 21 }
          - { dir: 1_21, mc: 1.21, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 21 }
          - { dir: 1_21, mc: 1.21, type: fabric, modloader: fabric, regex: .*fabric.*, java: 21 }
          - { dir: 1_20/1_20_6, mc: 1.20.6, type: lexforge, modloader: forge, regex: .*forge.*, java: 21 }
          - { dir: 1_20/1_20_6, mc: 1.20.6, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 21 }
          - { dir: 1_20/1_20_6, mc: 1.20.6, type: fabric, modloader: fabric, regex: .*fabric.*, java: 21 }
          - { dir: 1_20, mc: 1.20.4, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_20, mc: 1.20.4, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 17 }
          - { dir: 1_20, mc: 1.20.4, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_20, mc: 1.20.3, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_20, mc: 1.20.3, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 17 }
          - { dir: 1_20, mc: 1.20.3, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_20, mc: 1.20.2, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_20, mc: 1.20.2, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 17 }
          - { dir: 1_20, mc: 1.20.2, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_20/1_20_1, mc: 1.20.1, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_20/1_20_1, mc: 1.20.1, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_19, mc: 1.19.4, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_19, mc: 1.19.4, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_19, mc: 1.19.3, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_19, mc: 1.19.3, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_19, mc: 1.19.2, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_19, mc: 1.19.2, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_19, mc: 1.19.1, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_19, mc: 1.19.1, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_19, mc: 1.19, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_19, mc: 1.19, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_18, mc: 1.18.2, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { dir: 1_18, mc: 1.18.2, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { dir: 1_17, mc: 1.17.1, type: fabric, modloader: fabric, regex: .*fabric.*, java: 16 }
          - { dir: 1_17, mc: 1.17.1, type: lexforge, modloader: forge, regex: .*forge.*, java: 16 }
          - { dir: 1_16, mc: 1.16.5, type: fabric, modloader: fabric, regex: .*fabric.*, java: 8 }
          - { dir: 1_16, mc: 1.16.5, type: lexforge, modloader: forge, regex: .*forge.*, java: 8 }
          - { dir: 1_12, mc: 1.12.2, type: lexforge, modloader: forge, regex: .*forge.*, java: 8 }
          - { dir: 1_8_9, mc: 1.8.9, type: lexforge, modloader: forge, regex: .*orge.*, java: 8 }
          - { dir: 1_7_10, mc: 1.7.10, type: lexforge, modloader: forge, regex: .*orge.*, java: 8 }
    uses: 3arthqu4ke/mc-runtime-test/.github/workflows/run-specific-with-download-artifact-reusable.yml@main
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    with:
      dir: ${{ matrix.version.dir }}
      mc: ${{ matrix.version.mc }}
      type: ${{ matrix.version.type }}
      modloader: ${{ matrix.version.modloader }}
      regex: ${{ matrix.version.regex }}
      java: ${{ matrix.version.java }}
      headlessmc-command: '--retries 3 --jvm -Djava.awt.headless=true'
