name: Run latest version
on:
  workflow_dispatch:
  workflow_call:

jobs:
  run:
    strategy:
      matrix:
        version:
          - { dir: 1_20/1_20_6, mc: 1.20.6, type: lexforge, modloader: forge, regex: .*forge.*, java: 21 }
          - { dir: 1_20/1_20_6, mc: 1.20.6, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 21 }
          - { dir: 1_20/1_20_6, mc: 1.20.6, type: fabric, modloader: fabric, regex: .*fabric.*, java: 21 }
    uses: 3arthqu4ke/mc-runtime-test/.github/workflows/run-specific-reusable.yml@main
    with:
      dir: ${{ matrix.version.dir }}
      mc: ${{ matrix.version.mc }}
      type: ${{ matrix.version.type }}
      modloader: ${{ matrix.version.modloader }}
      regex: ${{ matrix.version.regex }}
      java: ${{ matrix.version.java }}
