name: Run latest gametests
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-gametest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
      - name: Grant execute permission for gametest gradlew
        working-directory: ./gametest
        run: chmod +x gradlew
      - name: Build Gametest
        working-directory: ./gametest
        run: ./gradlew build --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: gametest-jars
          path: ./gametest/build/libs/*.jar

  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
      - name: Grant execute permission for latest gradlew
        working-directory: ./1_20
        run: chmod +x gradlew
      - name: Build latest
        working-directory: ./1_20
        run: ./gradlew build --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: latest-jars
          path: ./1_20/build/libs/*.jar

  run:
    needs: [build-gametest, build-latest]
    strategy:
      matrix:
        version:
          - { dir: 1_20, mc: 1.20.6, type: lexforge, modloader: forge, regex: .*forge.*, java: 21 }
          - { dir: 1_20, mc: 1.20.6, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 21 }
          - { dir: 1_20, mc: 1.20.6, type: fabric, modloader: fabric, regex: .*fabric.*, java: 21 }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Make mods dir
        run: mkdir -p run/mods
      - name: Copy mod files
        run: |
          cp gametest-jars/clientgametest-1.20.6-2.4.1-fabric.jar run/mods
          cp gametest-jars/clientgametest-1.20.6-2.4.1-neoforge.jar run/mods
          cp gametest-jars/clientgametest-1.20.6-2.4.1-lexforge.jar run/mods
          cp latest-jars/mc-runtime-test-1.20.6-2.4.1-fabric-release.jar run/mods
          cp latest-jars/mc-runtime-test-1.20.6-2.4.1-lexforge-release.jar run/mods
          cp latest-jars/mc-runtime-test-1.20.6-2.4.1-neoforge-release.jar run/mods
      - name: Run game for version
        id: local-action
        uses: ./.github/actions/local-action
        with:
          mc-runtime-test: none
          headlessmc-command: --jvm "-Djava.awt.headless=true -DMcRuntimeGameTestMinExpectedGameTests=1"
          fabric-api: 0.97.0
          fabric-gametest-api: 1.3.5+85d85a934f
          checkout: false
