---
name: Run gametests

"on":
  workflow_dispatch: # TODO: add relevant inputs

jobs: # TODO: add cleanup job
  build:
    name: Build
    strategy:
      matrix:
        include:
          - { dir: gametest, mc: 1.20.4, lex: 49.0.38, neo: 219, java: 17 }
          - { dir: 1_20, mc: 1.20.4, lex: 49.0.38, neo: 219, java: 17 }
    uses: ./.github/workflows/flex-build.yml
    with:
      dir: ${{ matrix.dir }}
      mc: ${{ matrix.mc }}
      lex: ${{ matrix.lex }}
      neo: ${{ matrix.neo }}
      java: ${{ matrix.java }}

  merge: # TODO: simplify away this job
    name: Merge
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true

  run:
    name: Run tests
    needs: [merge]
    strategy:
      matrix:
        include:
          - { mc: 1.20.4, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.20.4, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 17 }
          - { mc: 1.20.4, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Stage artifacts
        run: |
          mkdir -p run/mods
          cp merged-artifacts/clientgametest-${{ matrix.mc }}-*-${{ matrix.type }}.jar run/mods
          cp merged-artifacts/mc-runtime-test-${{ matrix.mc }}-*-${{ matrix.type }}-release.jar run/mods

      - name: Setup temurin-${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Run game
        timeout-minutes: 3
        uses: ./
        with:
          mc: ${{ matrix.mc }}
          modloader: ${{ matrix.modloader }}
          regex: ${{ matrix.regex }}
          java: ${{ matrix.java }}
          mc-runtime-test: none
          headlessmc-command: --jvm "-Djava.awt.headless=true -DMcRuntimeGameTestMinExpectedGameTests=1"
          fabric-api: 0.97.0
          fabric-gametest-api: 1.3.5+85d85a934f
