name: Run the Minecraft Client
on:
  workflow_call:
    inputs:
      mc:
        description: 'The Minecraft version to run'
        required: true
        default: '1.20.4'
        type: string
      modloader:
        description: 'The modloader to install with HeadlessMc (forge, neoforge or fabric)'
        required: true
        default: 'forge'
        type: string
      regex:
        description: 'Regex to match the Minecraft version to launch (forge is like 1.20.4-forge and fabric starts with fabric-1.20)'
        required: true
        default: 'fabric.*1.20.4'
        type: string
      java:
        description: 'The Java version to use'
        required: true
        default: '17'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: actions/setup-java@v4
          with:
            java-version: ${{ inputs.java }}
            distribution: adopt
      -   name: Setup HeadlessMC directory
          run: mkdir HeadlessMC
      -   name: Configure HeadlessMC java versions
          run: echo hmc.java.versions=$JAVA_HOME/bin/java > HeadlessMC/config.properties
      -   name: Configure HeadlessMC game directory
          run: echo hmc.gamedir=$PWD/run >> HeadlessMC/config.properties
      -   name: Configure offline mode
          run: echo hmc.offline=true >> HeadlessMC/config.properties
      -   name: Configure Exceptions
          run: echo hmc.rethrow.launch.exceptions=true >> HeadlessMC/config.properties
      -   name: Configure Failing on wrong command
          run: echo hmc.exit.on.failed.command=true >> HeadlessMC/config.properties
      -   name: Configure Dummy Assets
          run: echo hmc.assets.dummy=true >> HeadlessMC/config.properties
      -   name: Get HeadlessMC
          run: wget -O headlessmc-launcher-1.9.4.jar https://github.com/3arthqu4ke/headlessmc/releases/download/1.9.4/headlessmc-launcher-1.9.4.jar
      -   name: Download ${{ inputs.mc }}
          run: java -jar headlessmc-launcher-1.9.4.jar --command download ${{ inputs.mc }}
      -   name: Download Fabric ${{ inputs.mc }}
          run: java -jar headlessmc-launcher-1.9.4.jar --command ${{ inputs.modloader }} ${{ inputs.mc }} --java ${{ github.event.inputs.java }}
      -   name: List versions
          run: java -jar headlessmc-launcher-1.9.4.jar --command versions
      -   name: Make mods dir
          run: mkdir -p run/mods
      -   name: Configure Accessibility
          run: echo onboardAccessibility:false >> run/options.txt
      -   name: LS mods dir
          run: ls run/mods
      -   name: Run game
          run: java -jar headlessmc-launcher-1.9.4.jar --command launch ${{ inputs.regex }} -regex -lwjgl --jvm -Djava.awt.headless=true
